
1st table--
		CREATE TABLE Flights(
					S_N INT,
					YEAR INT,
					MONTH INT,
					DAY INT,
					DAY_OF_WEEK INT,
					AIRLINE VARCHAR(10),
					FLIGHT_NUMBER INT,
					TAIL_NUMBER varchar(20),
					ORIGIN_AIRPORT varchar(20),
					DESTINATION_AIRPORT varchar(20),
					SCHEDULED_DEPARTURE INT,
					DEPARTURE_TIME INT,
					DEPARTURE_DELAY INT,
					TAXI_OUT INT,
					WHEELS_OFF INT,
					SCHEDULED_TIME INT,
					ELAPSED_TIME INT,
					AIR_TIME INT,
					DISTANCE INT,
					WHEELS_ON INT,
					TAXI_IN INT,
					SCHEDULED_ARRIVAL INT,
					ARRIVAL_TIME INT,
					ARRIVAL_DELAY INT,
					DIVERTED INT,
					CANCELLED INT,
					CANCELLATION_REASON VARCHAR(20)

);
second table--
CREATE TABLE Airlines(
			IATA_CODE Varchar(20),
			AIRLINE Varchar(40)					
);
third table
CREATE TABLE CANCELLATION_CODES(
				CANCELLATION_REASON varchar(5),
				CANCELLATION_DESCRIPTION varchar(20)
								
);
forth table
CREATE TABLE airports (
    IATA_CODE VARCHAR(10) PRIMARY KEY,
    AIRPORT VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    LATITUDE DECIMAL(10, 6),
    LONGITUDE DECIMAL(10, 6)
);

DROP TABLE airports;
